### ISSUE TITLE
Error Download

### ISSUE THREAD

**Issue by victorpinhors** [katomaro/Hotmart-download-bot#6]
Traceback (most recent call last):
File KatoMart.py", line 496, in
verCursos()
KatoMart.py", line 95, in verCursos
baixarCurso(authMart, cursosValidos[opcao], False)
File KatoMart.py", line 191, in baixarCurso
playerInfo = json.loads(BeautifulSoup(playerData, features="html.parser").find(
TypeError: 'NoneType' object is not subscriptable

**Comment by victorpinhors** [comment]
Por enquanto usa o https://www.mediafire.com/file/c32dnefg19x2n03/oCam_490_Portable.zip/file
mas tem q ficar olhando...


> Eu tive o mesmo erro aqui, segue imagem !
> 
> ![image](https://user-images.githubusercontent.com/5499444/136291059-20ed4efb-43c6-4121-8ea1-68605a636ffe.png)

**Comment by katomaro** [comment]
@victorpinhors me parece ser problema com a sua instalação do ffmpeg, consegue chamar ele pelo terminal normalmente?

**Comment by katomaro** [comment]
Talvez seja erro de path. Na pasta do script tem a pasta temporária com a dump.m3u8?  Se souber python, consegue colocar um print no self.save_path logo acima do subprocess.run(ffmpegcmd)? 

Deveras estranho, era para ir, as vezes adicionando "shell=True" dentro do .run() igual tem para Linux/macos resolva.

**Comment by victorpinhors** [comment]
> subprocess.run

Ihhh 
ae forçou meu conhecimento de Python...

Refiz o processo abaixo e funcionou agora!!

Baixei novamente o Python ( https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe )
Coloquei para reinstalar, marquei Py Laucher e na próxima tela marquei PreCompile standart library. Rodei novamente o pip intsall -r requeriments.txt

Rodei o KatoMart.py, loguei, escolhi o curso e começou a baixar.

Valeu Katomaro!!

**Comment by katomaro** [comment]
> > subprocess.run
> 
> Ihhh ae forçou meu conhecimento de Python...
> 
> Refiz o processo abaixo e funcionou agora!!
> 
> Baixei novamente o Python ( https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe ) Coloquei para reinstalar, marquei Py Laucher e na próxima tela marquei PreCompile standart library. Rodei novamente o pip intsall -r requeriments.txt
> 
> Rodei o KatoMart.py, loguei, escolhi o curso e começou a baixar.
> 
> Valeu Katomaro!!

Bom, que bom que aparentemente conseguiu, embora tenha sido um caso estranho. Vou fechar essa issue pois ela era causada pela alteração na plataforma, a forma de se passar o get, que foi corrigida.

**Comment by katomaro** [comment]
> > subprocess.run
> 
> Ihhh ae forçou meu conhecimento de Python...
> 
> Refiz o processo abaixo e funcionou agora!!
> 
> Baixei novamente o Python ( https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe ) Coloquei para reinstalar, marquei Py Laucher e na próxima tela marquei PreCompile standart library. Rodei novamente o pip intsall -r requeriments.txt
> 
> Rodei o KatoMart.py, loguei, escolhi o curso e começou a baixar.
> 
> Valeu Katomaro!!

Bom, que bom que aparentemente conseguiu, embora tenha sido um caso estranho. Vou fechar essa issue pois ela era causada pela alteração na plataforma, a forma de se passar o get, que foi corrigida.
